### ISSUE TITLE
 no matches found: .[dev]

### ISSUE THREAD

**Issue by bluzeey** [supercontrast-ai/supercontrast#22]
Was getting this error when I was following the second step of the readme.md. 

2. Install package

`pip install -e .[dev] `

**Comment by CarterMcClellan** [comment]
I see what went wrong this is a typo on our end! 

Can you try running

```
pip install -e .
```

while in the root dir of the package?

**Comment by bluzeey** [comment]
Yep @CarterMcClellan , that was able to work for me. After that i was able to run black and isort commands and the tests as well.
